server:
  port: 8000

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://discovery-service:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalTrackerFilter
          args:
            baseMessage: Spring Cloud Gateway Global Tracker Filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/fallback/user
        - id: mileage-service
          uri: lb://MILEAGE-SERVICE
          predicates:
            - Path=/mileage-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/mileage-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            - name: CircuitBreaker
              args:
                name: mileage-service
                fallbackuri: forward:/fallback/mileage
        - id: shop-service
          uri: lb://SHOP-SERVICE
          predicates:
            - Path=/shop-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/shop-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            - name: CircuitBreaker
              args:
                name: shop-service
                fallbackuri: forward:/fallback/shop
        - id: item-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/item-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/item-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            - name: CircuitBreaker
              args:
                name: item-service
                fallbackuri: forward:/fallback/item

management:
  endpoints:
    web:
      exposure:
        include: health, info

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa